=== cnippet-dev/ui-cnippet/apps/ui/public/schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "properties": {
    "aliases": {
      "properties": {
        "components": {
          "type": "string"
        },
        "hooks": {
          "type": "string"
        },
        "lib": {
          "type": "string"
        },
        "ui": {
          "type": "string"
        },
        "utils": {
          "type": "string"
        }
      },
      "required": ["utils", "components"],
      "type": "object"
    },
    "iconLibrary": {
      "type": "string"
    },
    "registries": {
      "additionalProperties": false,
      "patternProperties": {
        "^@": {
          "oneOf": [
            {
              "pattern": "\\{name\\}",
              "type": "string"
            },
            {
              "properties": {
                "headers": {
                  "additionalProperties": {
                    "type": "string"
                  },
                  "type": "object"
                },
                "params": {
                  "additionalProperties": {
                    "type": "string"
                  },
                  "type": "object"
                },
                "url": {
                  "pattern": "\\{name\\}",
                  "type": "string"
                }
              },
              "required": ["url"],
              "type": "object"
            }
          ]
        }
      },
      "type": "object"
    },
    "rsc": {
      "type": "boolean"
    },
    "style": {
      "enum": ["default", "new-york"],
      "type": "string"
    },
    "tailwind": {
      "properties": {
        "baseColor": {
          "type": "string"
        },
        "config": {
          "type": "string"
        },
        "css": {
          "type": "string"
        },
        "cssVariables": {
          "type": "boolean"
        },
        "prefix": {
          "type": "string"
        }
      },
      "required": ["config", "css", "baseColor", "cssVariables"],
      "type": "object"
    },
    "tsx": {
      "type": "boolean"
    }
  },
  "required": ["style", "tailwind", "rsc", "aliases"],
  "type": "object"
}

=== cnippet-dev/ui-cnippet/apps/ui/components.json
{
  "$schema": "https://ui.shadcn.com/schema.json",
  "aliases": {
    "components": "@/components",
    "hooks": "@/hooks",
    "lib": "@/lib",
    "motion": "@/components/motion",
    "ui": "@/components/ui",
    "utils": "@/lib/utils"
  },
  "iconLibrary": "lucide",
  "registries": {
    "@cnippet": "https://ui.cnippet.dev/r/{name}.json"
  },
  "rsc": true,
  "style": "new-york",
  "tailwind": {
    "baseColor": "neutral",
    "config": "",
    "css": "app/globals.css",
    "cssVariables": true,
    "prefix": ""
  },
  "tsx": true
}
